/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses;

import java.awt.event.KeyEvent;
import javax.swing.table.TableColumn;
import static GlobalVar.Var.*;

/**
 *
 * @author riki
 */
public class Jcari extends javax.swing.JFrame {

    /**
     * Creates new form Jcari
     */
    String query1,
            /**
             * Creates new form JcariBarangMasuk
             */
            /**
             * Creates new form Jcari
             */
            query2,
            /**
             * Creates new form JcariBarangMasuk
             */
            /**
             * Creates new form Jcari
             */
            judul1,
            /**
             * Creates new form JcariBarangMasuk
             */
            /**
             * Creates new form Jcari
             */
            judul2;
    Object selectedrow = null;
    int colnum;
    KomponenGUI.JtextF jf;
    KomponenGUI.JRibuanTextField jr;

    /**
     *
     * @param Query_pencarian_1
     * @param Query_Pencarian_2
     * @param Judul1_Pencarian_1
     * @param Judul2_Pencarian2
     * @param Title
     * @param Jf__parameter_untuk_isi_jtext_di_form_sbelumnya
     * @param FocusLeftOrRight__pilih_request_fokus_jtext_di_jcari
     */

    public Jcari(String Query1, String Query2, String Judul1, String Judul2, String Title, int Colnum, KomponenGUI.JtextF Jf, KomponenGUI.JRibuanTextField Jr, String FocusLeftOrRight) {
        jf = Jf;
        colnum = Colnum;
        query1 = Query1;
        query2 = Query2;
        judul1 = Judul1;
        judul2 = Judul2;
        jr = Jr;
        initComponents();
        if (FocusLeftOrRight != null) {
            JTCariNamaBarang.setText(FocusLeftOrRight);
            caridengannama();
            JTCariNamaBarang.requestFocus();
        } else {
            caridengankode();
        }
        setTitle(Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        JTCariNamaBarang.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTCariKodeBarang = new KomponenGUI.JtextF();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new KomponenGUI.JtableF();
        jbuttonF1 = new KomponenGUI.JbuttonF();
        jbuttonF2 = new KomponenGUI.JbuttonF();
        JTCariNamaBarang = new KomponenGUI.JtextFnoSelect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JTCariKodeBarang.setForeground(new java.awt.Color(153, 153, 153));
        JTCariKodeBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTCariKodeBarangFocusGained(evt);
            }
        });
        JTCariKodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTCariKodeBarangKeyReleased(evt);
            }
        });

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                judul1, judul2
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbldataMouseReleased(evt);
            }
        });
        tbldata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbldataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbldata);

        jbuttonF1.setText("PILIH");
        jbuttonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF1ActionPerformed(evt);
            }
        });

        jbuttonF2.setText("KEMBALI");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        JTCariNamaBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTCariNamaBarangFocusGained(evt);
            }
        });
        JTCariNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTCariNamaBarangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTCariKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTCariNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTCariKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTCariNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTCariKodeBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCariKodeBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jf.setText(tbldata.getValueAt(tbldata.getSelectedRow(), colnum).toString());
            jr.requestFocus();
            dispose();
            jcari = null;
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tbldata.requestFocus();
            if (tbldata.getSelectedRow() == 0) {
                tbldata.setRowSelectionInterval(1, 1);
            }
        } else {
            caridengankode();
        }
    }//GEN-LAST:event_JTCariKodeBarangKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jcari = null;
    }//GEN-LAST:event_formWindowClosing

    private void jbuttonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF1ActionPerformed
        jf.setText(tbldata.getValueAt(tbldata.getSelectedRow(), colnum).toString());
        jr.requestFocus();
        dispose();
        jcari = null;
    }//GEN-LAST:event_jbuttonF1ActionPerformed

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed
        jr.requestFocus();
        dispose();
        jcari = null;
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void tbldataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseReleased
        if (tbldata.getValueAt(tbldata.getSelectedRow(), colnum) == selectedrow) {
            jf.setText(tbldata.getValueAt(tbldata.getSelectedRow(), colnum).toString());
            jr.requestFocus();
            dispose();
            jcari = null;
        } else {
            selectedrow = tbldata.getValueAt(tbldata.getSelectedRow(), colnum);
        }
    }//GEN-LAST:event_tbldataMouseReleased

    private void JTCariNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCariNamaBarangKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jf.setText(tbldata.getValueAt(tbldata.getSelectedRow(), colnum).toString());
            jr.requestFocus();
            dispose();
            jcari = null;
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tbldata.requestFocus();
            if (tbldata.getSelectedRow() == 0) {
                tbldata.setRowSelectionInterval(1, 1);
            }
        } else {
            caridengannama();
        }

    }//GEN-LAST:event_JTCariNamaBarangKeyReleased

    private void tbldataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbldataKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jf.setText(tbldata.getValueAt(tbldata.getSelectedRow(), colnum).toString());
            jr.requestFocus();
            dispose();
            jcari = null;
        }
    }//GEN-LAST:event_tbldataKeyPressed

    private void JTCariKodeBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTCariKodeBarangFocusGained
        caridengankode();
    }//GEN-LAST:event_JTCariKodeBarangFocusGained

    private void JTCariNamaBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTCariNamaBarangFocusGained
        caridengannama();
    }//GEN-LAST:event_JTCariNamaBarangFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static KomponenGUI.JtextF JTCariKodeBarang;
    private KomponenGUI.JtextFnoSelect JTCariNamaBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private KomponenGUI.JbuttonF jbuttonF1;
    private KomponenGUI.JbuttonF jbuttonF2;
    private KomponenGUI.JtableF tbldata;
    // End of variables declaration//GEN-END:variables

    void caridengankode() {
        if (JTCariKodeBarang.getText().equals("")) {
            tbldata.setQuery(query1 + "LIKE '%" + JTCariKodeBarang.getText() + "%'");
        } else {
            tbldata.setQuery(query1 + "REGEXP '" + JTCariKodeBarang.getText().replace(" ", ".+") + "'");
        }
        tbldata.tampilkan();
        TableColumn tableColumn = tbldata.getColumnModel().getColumn(0);
        tableColumn.setPreferredWidth(90);
        if (tbldata.getRowCount() != 0) {
            tbldata.setRowSelectionInterval(0, 0);
        }
    }

    void caridengannama() {
        if (JTCariNamaBarang.getText().equals("")) {
            tbldata.setQuery(query2 + "LIKE '%" + JTCariNamaBarang.getText() + "%'");
        } else {
            tbldata.setQuery(query2 + "REGEXP '" + JTCariNamaBarang.getText().replace(" ", ".+") + "'");
        }
        tbldata.tampilkan();
        TableColumn tableColumn = tbldata.getColumnModel().getColumn(0);
        tableColumn.setPreferredWidth(90);
        if (tbldata.getRowCount() != 0) {
            tbldata.setRowSelectionInterval(0, 0);
        }
    }

}
